# Generated by ChatGPT - manual migration to add is_bot field
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
