# Generated by Django 5.1.2 on 2025-10-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_product_stock_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
